spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco
    username: root
    password:   Deusmeu19

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect